version: 0.2

phases:
  build:
    commands:
      - cp lambda_handler/sample_lambda_handler.py .

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    CFNArtifact:
      base-directory: $CODEBUILD_SRC_DIR
      files:
        - SampleLambdaTemplate.json
    sourceArtifact:
      base-directory: $CODEBUILD_SRC_DIR
      files:
        - sample_lambda_handler.py